[package]
name = "kuliya"
version = "0.1.0"
edition = "2021"

[features]
default = ["const"]
const = []

[dependencies]

[build-dependencies]
serde = { version = "1.0.194", features = ["derive"] }
serde_json = { version = "1.0.110", features = ["preserve_order"] }
