name: C Checks

on:
  pull_request:
    paths:
      - ".github/workflows/c-checks.yml"
      - "c/**"

jobs:
  build_and_test:
    name: kuliya - latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.2

      - name: Create default profile
        run: conan profile detect --force

      - name: Install dependencies
        run: |
          cd c
          conan install . --output-folder=build --build=missing

      - name: Set up build environment
        run: |
          cd c/build
          sh conanbuild.sh
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          make build
          cd ..
          ./build/build

      - name: Build all targets
        run: |
          cd c/build
          make all

      - name: Run tests
        run: |
          cd c
          ctest

      - name: Run example
        run: |
          cd c
          ./build/example
