name: C publish Doxygen

on:
  workflow_dispatch:

jobs:
  build_docs_and_publish:
    name: kuliya - latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docs with Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'c/'
          doxyfile-path: 'Doxyfile'

      - name: Publish to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./c/docs/html
