name: D Checks

on:
  pull_request:
    paths:
      - ".github/workflows/d-checks.yml"
      - "d/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7

      - name: Build data.d
        run: |
          cd d/build
          dub

      - name: Run tests
        run: |
          cd d
          dub test
