name: "Rust Checks"

on:
  pull_request:
    paths:
      - ".github/workflows/rust-checks.yml"
      - "rust/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: kuliya - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cd rust && cargo build --verbose
      - run: cd rust && cargo test --verbose
      - run: cd rust && cargo test --verbose --features serde_derive
      - run: cd rust && cargo test --verbose --no-default-features --features storage
