name: "Rust Checks"

on:
  pull_request:
    paths:
      - ".github/workflows/rust-checks.yml"
      - "rust/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: kuliya - latest
    runs-on: ubuntu-latest
    env:
      CWD: "rust"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo install cargo-readme
      - run: cargo readme > README.md
        working-directory: ${{ env.CWD }}
      - run: cargo clippy --all-features -- -Dwarnings
        working-directory: ${{ env.CWD }}
      - run: cargo build --verbose
        working-directory: ${{ env.CWD }}
      - name: "is docs updated and generated files are committed"
        run: git diff --exit-code
      - run: cargo test --verbose
        working-directory: ${{ env.CWD }}
      - run: cargo test --verbose --lib --bins --tests --features serde_derive
        working-directory: ${{ env.CWD }}
      - run: cargo test --verbose  --lib --bins --tests --no-default-features --features storage
        working-directory: ${{ env.CWD }}
      - run: cargo test --verbose --all-features
        working-directory: ${{ env.CWD }}
